url: https://verizondigital.github.io/hyperion
baseurl: /hyperion
safe: true
lsi: false
source: .
destination: ./public
encoding: UTF-8

# github pages we cannot customize
lsi: false
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji
incremental: false
gist:
  noscript: false
# customize github pages
quiet: false
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: false
  template: '' # cannot customize
  math_engine: mathjax # cannot customize
  syntax_highligher: rouge # cannot customize

plugins:
  - jekyll-redirect-from

exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - ./public

host: 0.0.0.0
port: 9876

latest_version: 1.0

navigation:
- title: Versions
  url: /versions/
- title: Github
  url: https://github.com/VerizonDigital/hyperion